name: Run markdown lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install remark-cli and remark-preset-lint-consistent
        run: |
          npm install remark-cli remark-preset-lint-consistent

      - name: Run markdown lint
        run: npx remark . --use remark-preset-lint-consistent --frail

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
